"""empty message

Revision ID: 2b447c31d73b
Revises: 
Create Date: 2021-02-09 23:33:00.725252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b447c31d73b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrinhos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor_frete', sa.Integer(), nullable=False),
    sa.Column('valor_total', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.Column('preco', sa.Integer(), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('senha', sa.String(length=20), nullable=False),
    sa.Column('cpf', sa.Integer(), nullable=False),
    sa.Column('nascimento', sa.String(length=10), nullable=False),
    sa.Column('telefone', sa.Integer(), nullable=False),
    sa.Column('telefone_opicional', sa.Integer(), nullable=True),
    sa.Column('carrinho_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carrinho_id'], ['carrinhos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('enderecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cep', sa.Integer(), nullable=False),
    sa.Column('logadouro', sa.String(length=30), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=20), nullable=False),
    sa.Column('cidade', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagens_produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Integer(), nullable=False),
    sa.Column('valor_total', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id', 'valor_unitario', 'valor_total')
    )
    op.create_table('association_carrinhos_produtos_compra',
    sa.Column('produtos_compra', sa.Integer(), nullable=True),
    sa.Column('carrinhos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carrinhos'], ['carrinhos.id'], ),
    sa.ForeignKeyConstraint(['produtos_compra'], ['produtos_compra.id'], )
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('pagamento_aprovado', sa.Boolean(), nullable=False),
    sa.Column('valor_frete', sa.Integer(), nullable=False),
    sa.Column('valor_total', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('endereco_entrega_id', sa.Integer(), nullable=True),
    sa.Column('endereco_cobranca_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['endereco_cobranca_id'], ['enderecos.id'], ),
    sa.ForeignKeyConstraint(['endereco_entrega_id'], ['enderecos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id', 'valor_frete', 'valor_total')
    )
    op.create_table('association_pedidos_produtos_compra',
    sa.Column('produtos_compra', sa.Integer(), nullable=True),
    sa.Column('pedidos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pedidos'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['produtos_compra'], ['produtos_compra.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_pedidos_produtos_compra')
    op.drop_table('pedidos')
    op.drop_table('association_carrinhos_produtos_compra')
    op.drop_table('produtos_compra')
    op.drop_table('imagens_produtos')
    op.drop_table('enderecos')
    op.drop_table('usuarios')
    op.drop_table('produtos')
    op.drop_table('carrinhos')
    # ### end Alembic commands ###
